sudo: required
language: node_js
dist: "focal"
node_js: 18
services:
  - docker

before_install:
  - docker login -u="${DOCKER_USER}" -p="${DOCKER_PASSWORD}"
  - docker build -t front_app:latest ./frontend/nuxt-app/
  - docker images 
  - docker tag front_app front_app:latest
  - docker push thegostisdead/front_app:latest

script:
  - echo "skipping tests"
