sudo: required
language: node_js
dist: "focal"
node_js: 18
services:
  - docker
addons:
  ssh_known_hosts: ${SERVER_IP_ADDRESS}
  apt:
    packages:
    - sshpass

before_install:
  - docker login -u="${DOCKER_USER}" -p="${DOCKER_PASSWORD}"
#  - docker build -t front_app:latest ./frontend/nuxt-app/
#  - docker images 
#  - docker tag front_app:latest thegostisdead/front_app:latest
#  - docker push thegostisdead/front_app:latest

after_success:  
  - eval "$(ssh-agent -s)"
  - echo -e "Host ${SERVER_IP_ADDRESS}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - sshpass -p '${SERVER_PASSWORD}' ssh -o StrictHostKeyChecking=no ${SERVER_USER}@${SERVER_IP_ADDRESS} "docker run -p 8080:8080 --name=frontend -d thegostisdead/front_app:latest"  
    
script:
  - echo "skipping tests"
