sudo: required
language: node_js
dist: "focal"
node_js: 18
services:
  - docker

before_install:
  - docker build -t frontend ./frontend/nuxt-app/
script:
  - echo "skipping tests"

deploy:
  provider: elasticbeanstalk
  region: "eu-west-3"
  app: "bootstrap-devops"
  env: "bootstrapdevops-env"
  bucket_name: "s3-bootstrap-thegostisdead"
  bucket_path: "app"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"